name: build-wheel-cuda-310

on:
  push:
    tags:
    - 'v**'

jobs:
  build-and-deploy-linux:
    name: Build wheel CUDA 3.10 (manylinux)
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    env:
      CIBW_ENVIRONMENT: TORCH_VERSION_SPECIFIER="==2.9.0" MAKEFLAGS="-j4" USE_CUDA=ON
      CIBW_BUILD: cp310-manylinux_x86_64
      CIBW_BEFORE_ALL: >
        yum install -y openblas-devel
      CIBW_BEFORE_BUILD: >
        pip install torch==2.9.0 torchvision==0.24.0 torchaudio==2.9.0 --index-url https://download.pytorch.org/whl/cu126
        && pip install -r requirements.txt
      CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
      CIBW_REPAIR_WHEEL_COMMAND: >
        auditwheel repair -w {dest_dir} {wheel} --exclude libtorch_python.so
    steps:
      - uses: actions/checkout@v3

      - name: Pull manylinux image
        run: docker pull $CIBW_MANYLINUX_X86_64_IMAGE

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels (per version)
        uses: actions/upload-artifact@v4
        with:
          name: wheel_cuda_py310
          path: wheelhouse/*.whl
