name: build-wheel-312

on:
  workflow_dispatch:
  push:
    tags:
    - 'v**'

jobs:
  build-and-deploy-linux:
    name: Build wheel 3.12 (manylinux)
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    env:
      CIBW_BUILD: cp312-manylinux_x86_64
      CIBW_BUILD_FRONTEND: "pip; args: --no-build-isolation"
      CIBW_BEFORE_ALL: >
        yum install -y openblas-devel
      CIBW_BEFORE_BUILD: |
        pip install \
          "cmake>=4.2.1" \
          "scikit-build>=0.18.1" \
          scikit-learn \
          "pybind11>=3.0.1" \
          "torch>=2.9.1" \
          torchvision \
          scipy \
          "requests>=2.32,<3" \
          numpy \
          protobuf \
          tqdm \
          mypy
      CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
      CIBW_REPAIR_WHEEL_COMMAND: >
        auditwheel repair -w {dest_dir} {wheel} --exclude libtorch_python.so
    steps:
      - uses: actions/checkout@v3

      - name: Pull manylinux image
        run: docker pull $CIBW_MANYLINUX_X86_64_IMAGE

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.3.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels (per version)
        uses: actions/upload-artifact@v4
        with:
          name: wheel_py312
          path: wheelhouse/*.whl
