name: build-wheel-310

on:
  workflow_dispatch:
  push:
    tags:
    - 'v**'

jobs:
  build-and-deploy-linux:
    name: Build wheel 3.10 (manylinux)
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    env:
      CIBW_BUILD: cp310-manylinux_x86_64
      CIBW_BEFORE_ALL: >
        yum install -y openblas-devel gcc-toolset-12 &&
        source /opt/rh/gcc-toolset-12/enable
      CIBW_ENVIRONMENT: >
        PATH="/opt/rh/gcc-toolset-12/root/usr/bin:$PATH"
        LD_LIBRARY_PATH="/opt/rh/gcc-toolset-12/root/usr/lib64:$LD_LIBRARY_PATH"
        CC=/opt/rh/gcc-toolset-12/root/usr/bin/gcc
        CXX=/opt/rh/gcc-toolset-12/root/usr/bin/g++
      CIBW_BEFORE_BUILD: |
        pip install \
          "cmake>=4.2.1" \
          "scikit-build>=0.18.1" \
          scikit-learn \
          "pybind11>=3.0.1" \
          "torch>=2.9.1" \
          torchvision \
          scipy \
          "requests>=2.32,<3" \
          numpy \
          protobuf \
          tqdm \
          mypy
      CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
      CIBW_REPAIR_WHEEL_COMMAND: >
        auditwheel repair -w {dest_dir} {wheel} --exclude libtorch_python.so
    steps:
      - uses: actions/checkout@v3

      - name: Pull manylinux image
        run: docker pull $CIBW_MANYLINUX_X86_64_IMAGE

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels (per version)
        uses: actions/upload-artifact@v4
        with:
          name: wheel_py310
          path: wheelhouse/*.whl
