name: build-wheels

on: [push, pull_request]

jobs:
  build-and-deploy-linux:
    name: Build wheels (manylinux)
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    env:
      CIBW_BUILD: cp310-* cp311-* cp312-*
      CIBW_BEFORE_ALL: >
        yum install -y openblas-devel
      CIBW_BEFORE_BUILD: >
        rm -rf build/ _skbuild/ src/aihwkit/simulator/rpu_base*.so src/aihwkit/extension/*.so *.egg-info
        && echo "Cleaned build dirs"
        && pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        && pip install -r requirements.txt
      CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux2014_x86_64"
      CIBW_REPAIR_WHEEL_COMMAND: >
        auditwheel repair -w {dest_dir} {wheel} --exclude libtorch_python.so
    steps:
      - uses: actions/checkout@v3

      - name: Pull manylinux image
        run: docker pull $CIBW_MANYLINUX_X86_64_IMAGE

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels (per version)
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*.whl
